// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContainerPathStat ContainerPathStat is used to describe the stat of file
// swagger:model ContainerPathStat

type ContainerPathStat struct {

	// link target
	LinkTarget string `json:"linkTarget,omitempty"`

	// mode
	Mode uint32 `json:"mode,omitempty"`

	// modification time.
	Mtime strfmt.DateTime `json:"mtime,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// size
	Size string `json:"size,omitempty"`
}

/* polymorph ContainerPathStat linkTarget false */

/* polymorph ContainerPathStat mode false */

/* polymorph ContainerPathStat mtime false */

/* polymorph ContainerPathStat name false */

/* polymorph ContainerPathStat size false */

// Validate validates this container path stat
func (m *ContainerPathStat) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerPathStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerPathStat) UnmarshalBinary(b []byte) error {
	var res ContainerPathStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
